# Generated by Django 6.0.5 on 2026-05-17 14:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EssayCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Essay Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the essay', max_length=255)),
                ('prompt', models.TextField(blank=True, help_text='Prompt or question the essay is responding to', null=True)),
                ('body_text', models.TextField(help_text='Main content of the essay')),
                ('target_words', models.PositiveBigIntegerField(default=500, help_text='Target word count for the essay')),
                ('author_tag', models.CharField(db_index=True, help_text='Tag to identify the author of the essay', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('ARCHIVED', 'Archived')], default='SUBMITTED', max_length=20)),
                ('language', models.CharField(default='en', help_text='Language of the essay', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essays', to='analyzer.essaycategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EssayMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_count', models.PositiveBigIntegerField(default=0)),
                ('sentence_count', models.PositiveBigIntegerField(default=0)),
                ('character_count', models.PositiveBigIntegerField(default=0)),
                ('syllable_count', models.PositiveBigIntegerField(default=0)),
                ('grade_level', models.FloatField(default=0.0)),
                ('reading_ease', models.FloatField(default=0.0)),
                ('vocab_complexity', models.FloatField(default=0.0, help_text='Average syllables per word or similar metric')),
                ('lexical_diversity', models.FloatField(default=0.0, help_text='Unique words / total words')),
                ('cohesion_score', models.FloatField(default=0.0)),
                ('passive_voice_percentage', models.FloatField(default=0.0)),
                ('avg_sentence_length', models.FloatField(default=0.0)),
                ('avg_word_length', models.FloatField(default=0.0)),
                ('structural_feedback', models.JSONField(default=list, help_text='List of actionable feedback points related to structure')),
                ('overall_score', models.FloatField(default=0.0, help_text='Overall quality score based on combined metrics')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('essay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analyzer.essay')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='essay',
            index=models.Index(fields=['author_tag'], name='analyzer_es_author__6a9131_idx'),
        ),
        migrations.AddIndex(
            model_name='essay',
            index=models.Index(fields=['status'], name='analyzer_es_status_c0b735_idx'),
        ),
        migrations.AddIndex(
            model_name='essay',
            index=models.Index(fields=['created_at'], name='analyzer_es_created_723a30_idx'),
        ),
    ]
